FROM docker.io/library/alpine:3.24

RUN apk --no-cache upgrade && apk --no-cache add ca-certificates git

ARG TARGETOS
ARG TARGETARCH
COPY ${TARGETOS}/${TARGETARCH}/genver /usr/local/bin/genver

ENTRYPOINT ["/usr/local/bin/genver"]
